# Generated by Django 4.2.7 on 2023-12-08 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=255)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('foto_perfil', models.ImageField(blank=True, default='static/images/media/user.png', null=True, upload_to='static/images/media')),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Transgênero', 'Transgênero'), ('Gênero Neutro', 'Gênero Neutro'), ('Não-binário', 'Não-binário'), ('Prefiro não responder', 'Prefiro não responder'), ('Outro', 'Outro')], max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
