# Generated by Django 4.2.7 on 2023-12-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Transgênero', 'Transgênero'), ('Gênero Neutro', 'Gênero Neutro'), ('Não-binário', 'Não-binário'), ('Prefiro não responder', 'Prefiro não responder'), ('Outro', 'Outro')], default='Outro', max_length=100),
        ),
    ]
