# Generated by Django 4.2.7 on 2023-11-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('sopro', 'Sopro'), ('cordas', 'Cordas'), ('percussão', 'Percussão')], max_length=50)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('emprestado', 'Emprestado'), ('defeito', 'Com defeito')], default='disponivel', max_length=50)),
            ],
        ),
    ]
