# Generated by Django 4.2.6 on 2023-11-17 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrumento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico_responsavel', models.CharField(max_length=100)),
                ('descricao_servico', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_conclusao', models.DateField()),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumento.instrumento')),
            ],
        ),
    ]
