# Generated by Django 4.2.7 on 2023-11-28 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defeito', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_servico', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_conclusao', models.DateField(null=True)),
                ('defeito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defeito.defeito')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
